// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// ReaderController is an autogenerated mock type for the ReaderController type
type ReaderController struct {
	mock.Mock
}

// Feed provides a mock function with given fields: w, r
func (_m *ReaderController) Feed(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// Fetch provides a mock function with given fields: w, r
func (_m *ReaderController) Fetch(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// FetchById provides a mock function with given fields: w, r
func (_m *ReaderController) FetchById(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// FetchConcurrently provides a mock function with given fields: w, r
func (_m *ReaderController) FetchConcurrently(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// UpdateUsersFromFeed provides a mock function with given fields: w, r
func (_m *ReaderController) UpdateUsersFromFeed(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}
