// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	types "Go-Dispatch-Bootcamp/types"

	mock "github.com/stretchr/testify/mock"
)

// ReaderService is an autogenerated mock type for the ReaderService type
type ReaderService struct {
	mock.Mock
}

// FetchCsvFromRemote provides a mock function with given fields: _a0
func (_m *ReaderService) FetchCsvFromRemote(_a0 string) ([][]string, error) {
	ret := _m.Called(_a0)

	var r0 [][]string
	if rf, ok := ret.Get(0).(func(string) [][]string); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFeed provides a mock function with given fields: _a0
func (_m *ReaderService) GetFeed(_a0 string) ([][]string, error) {
	ret := _m.Called(_a0)

	var r0 [][]string
	if rf, ok := ret.Get(0).(func(string) [][]string); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: _a0
func (_m *ReaderService) Get(_a0 string) (*[]types.User, error) {
	ret := _m.Called(_a0)

	var r0 *[]types.User
	if rf, ok := ret.Get(0).(func(string) *[]types.User); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]types.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetConcurrently provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *ReaderService) GetConcurrently(_a0 string, _a1 string, _a2 int, _a3 int) (*[]types.User, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	var r0 *[]types.User
	if rf, ok := ret.Get(0).(func(string, string, int, int) *[]types.User); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]types.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, int, int) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMap provides a mock function with given fields: _a0
func (_m *ReaderService) GetMap(_a0 string) (map[int]types.User, error) {
	ret := _m.Called(_a0)

	var r0 map[int]types.User
	if rf, ok := ret.Get(0).(func(string) map[int]types.User); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[int]types.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: _a0, _a1
func (_m *ReaderService) Update(_a0 *[]types.User, _a1 string) (bool, error) {
	ret := _m.Called(_a0, _a1)

	var r0 bool
	if rf, ok := ret.Get(0).(func(*[]types.User, string) bool); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*[]types.User, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
